import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import getConfig from "next/config";

const inter = Inter({ subsets: ["latin"] });



export const metadata = {
  title: "nerdBlogBytes",
  description: "Generated by create next app",
  favicon: '/favicon.ico'

};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
     
      <body className={inter.className} suppressHydrationWarning={true}>{children}</body>
    </html>
  );
}
